### ISSUE TITLE
Question: Why rack-jekyll finds file from long string?

### ISSUE THREAD

**Issue by sorah** [adaoraul/rack-jekyll#23]
https://github.com/adaoraul/rack-jekyll/blob/master/lib/rack/jekyll.rb#L69-L70

`@files.include?(path_info)` seems to be for find proper file to render. but, `@files` is a String generated by `Array#inspect`.

Using `String#include?` leads to match partial path.

``` ruby
path_info = "/b"
p ["_site/a/b/c"].inspect.include?(path_info) #=> true
p ["_site/a/b/c"].include?(path_info) #=> false
```

so in this case, when user requested to `/b` that doesn't exist, rack-jekyll returns error like the following

```
No such file or directory @ rb_sysopen - www.ruby-lang.org/_site/b/index.html
App 9033 stderr:        from rack-jekyll-0.4.1/lib/rack/jekyll/helpers.rb:14:in `initialize'
App 9033 stderr:        from rack-jekyll-0.4.1/lib/rack/jekyll/helpers.rb:14:in `open'
App 9033 stderr:        from rack-jekyll-0.4.1/lib/rack/jekyll/helpers.rb:14:in `file_info'
App 9033 stderr:        from rack-jekyll-0.4.1/lib/rack/jekyll.rb:77:in `call'
App 9033 stderr:        from rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 9033 stderr:        from rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 9033 stderr:        from rack-rewrite-1.5.0/lib/rack/rewrite.rb:24:in `call'
App 9033 stderr:        from rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
```

I guess this is bug... but I guess there's some reason to use `inspect` maybe, so I'm asking question before pull-request.

Thoughts?

**Comment by stomar** [comment]
Fixed with a9eb164d6c1ec548aa1ce3fc18e6f9f209d01487.
