### ISSUE TITLE
[jekyll 3.2.0]static_file.rb 149 `utime': No such file or directory 

### ISSUE THREAD

**Issue by jnozsc** [adaoraul/rack-jekyll#49]
when using jekyll 3.2+

here is the console output for `heroku logs`

```
2016-07-28T02:51:37.297835+00:00 app[web.1]: Generating site: /app -> /app/_site
2016-07-28T02:51:37.371747+00:00 heroku[web.1]: Process exited with status 1
2016-07-28T02:51:37.386510+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-28T02:51:37.387493+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-28T02:51:39.161559+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 30370`
2016-07-28T02:51:52.026687+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:149:in `utime': No such file or directory @ utime_internal - /app/_site/bin/erb (Errno::ENOENT)
2016-07-28T02:51:52.026709+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:149:in `copy_file'
2016-07-28T02:51:52.026711+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/static_file.rb:93:in `write'
2016-07-28T02:51:52.026712+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:212:in `block in write'
2016-07-28T02:51:52.026721+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:211:in `write'
2016-07-28T02:51:52.026719+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `block in each_site_file'
2016-07-28T02:51:52.026721+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each_site_file'
2016-07-28T02:51:52.026722+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:71:in `process'
2016-07-28T02:51:52.026714+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `each'
2016-07-28T02:51:52.026724+00:00 app[web.1]:    from /app/config.ru:3:in `new'
2016-07-28T02:51:52.026713+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:333:in `block (2 levels) in each_site_file'
2016-07-28T02:51:52.026723+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-jekyll-0.4.5/lib/rack/jekyll.rb:44:in `initialize'
2016-07-28T02:51:52.026726+00:00 app[web.1]:    from /app/config.ru:in `new'
2016-07-28T02:51:52.026725+00:00 app[web.1]:    from /app/config.ru:3:in `block in <main>'
2016-07-28T02:51:52.026726+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2016-07-28T02:51:52.026729+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2016-07-28T02:51:52.026720+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each'
2016-07-28T02:51:52.026729+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2016-07-28T02:51:52.026725+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2016-07-28T02:51:52.026723+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-jekyll-0.4.5/lib/rack/jekyll.rb:110:in `process'
2016-07-28T02:51:52.026727+00:00 app[web.1]:    from /app/config.ru:in `<main>'
2016-07-28T02:51:52.026732+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2016-07-28T02:51:52.026734+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2016-07-28T02:51:52.026731+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2016-07-28T02:51:52.026731+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2016-07-28T02:51:52.026735+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
2016-07-28T02:51:52.026730+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2016-07-28T02:51:52.038753+00:00 app[web.1]: Generating site: /app -> /app/_site
2016-07-28T02:51:52.026739+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/bin/rackup:23:in `load'
2016-07-28T02:51:52.026736+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
2016-07-28T02:51:52.038751+00:00 app[web.1]: Configuration file: /app/_config.yml
2016-07-28T02:51:52.026740+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.3.0/bin/rackup:23:in `<main>'
2016-07-28T02:51:52.158547+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by jnozsc** [comment]
original post in jekyll
https://github.com/jekyll/jekyll/issues/5144

**Comment by stomar** [comment]
This is not rack-jekyll specific.

For Jekyll 3.2.0 we observe the same behaviour on Heroku while trying to deploy www.ruby-lang.org using [lanyon](https://github.com/stomar/lanyon), which --- just like rack-jekyll --- relies on Jekyll::Site#process to build the site. Jekyll versions before 3.2.0 worked just fine.
